name = "FlatBuffersTypeSerializers"
uuid = "c13d007d-c62b-4dc1-adbf-dd9e67a39354"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
FlatBuffers = "53afe959-3a16-52fa-a8da-cf864710bae9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
